config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  resources :categories
  resources :orders
  resources :line_items
  resources :carts
  resources :products
  resources :products
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'

  get '/help', to: 'static_pages#help'

  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/admin', to: 'orders#admin'
  get '/search', to: 'products#search'
  mount Sidekiq::Web => '/sidekiq'
  resources :microposts
  resources :users
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :account_activations, only: [:edit]

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      if current_item.quantity < current_item.product.stock
        current_item.quantity += 1
      end
    else
      current_item = line_items.build(product_id: product_id)
      current_item.price = current_item.product.price
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    add_breadcrumb "Home", root_path
    add_breadcrumb "cart"
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        flash[:success] = 'Cart was successfully created'
        redirect_to @cart
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div class="row" class="cart">
    <div class="col-sm-12 col-md-10 col-md-offset-1">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th class="text-center">Price</th>
                    <th class="text-center">Total</th>
                    <th> </th>
                </tr>
            </thead>
            <tbody>
                <% cart.line_items.includes(:product).each do |item| %>
                  <tr>
                      <td class="col-sm-4 col-md-6 col-xs-3">
                      <div class="media">
                        <%= image_tag item.product.image_url :xs_icon, class: "thumbnail pull-left" %>
                          <div class="media-body">
                              <h4 class="media-heading"><a href="#"><%= item.product.title %></a></h4>
                              <span>Status: </span><span class="text-success">
                              <strong>
                                      <% if item.product.stock < 0 %>
                                        Out of Stock
                                      <%else %>
                                        In Stock: <span class="stock"><%= item.product.stock %> </span>
                                      <%end%>
                                </strong></span>
                          </div>
                      </div></td>
                      <td class="col-sm-1 col-md-1 col-xs-1" style="text-align: center">
                      <%= form_tag line_item_path(item), method: :patch, remote: true do %>
                        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

                        <%= number_field_tag :quantity, item.quantity, class: "form-control", min: 1, max: item.product.stock, onchange: "this.form.submit()"%>
                      <%end%>
                      </td>

                      <td class="col-sm-1 col-md-1 text-center col-xs-1"><strong>$<%= item.product.price %></strong></td>
                      <td class="col-sm-1 col-md-1 text-center col-xs-1"><strong>$<%= item.quantity * item.product.price%></strong></td>
                      <td class="col-sm-1 col-md-1 col-xs-1">
                         <%= button_to line_item_path(item), method: :delete,
                          data: { confirm: 'Are you sure?' } , class: "btn btn-danger" do%>
                          Remove <span class="glyphicon glyphicon-remove"></span>
                        <% end %>
                      </td>
                  </tr>
                <% end %>
                <tr>
                    <td>   </td>
                    <td>   </td>
                    <td>   </td>
                    <td><h3>Total</h3></td>
                    <td class="text-right col-sm-1 col-md-1 col-xs-1"><h3><strong><%= number_to_currency(cart.total_price) %></strong></h3></td>
                </tr>
                <tr>
                    <td>   </td>
                    <td>   </td>
                    <td class="col-sm-1 col-md-1 col-xs-1">
                      <%= button_to root_path,method: :get, class: "btn btn-default" do%>
                        <span class="glyphicon glyphicon-shopping-cart"></span> Continue Shopping
                      <%end %>
                    </td>
                    <td class="col-sm-1 col-md-1 col-xs-1">
                        <%= button_to cart, method: :delete,
                          data: { confirm: 'Are you sure?' } , class: "btn btn-danger" do%>
                          Clear Cart <span class="glyphicon glyphicon-play"></span>
                        <% end %>
                    </td>

                    <td class="col-sm-1 col-md-1 col-xs-1">
                      <%= button_to new_order_path, method: :get, class: "btn btn-success checkout_cart" do%>
                        Checkout <span class="glyphicon glyphicon-play"></span>
                      <%end %>

                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<%= render(@cart) %>