config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  resources :categories
  resources :orders
  resources :line_items
  resources :carts
  resources :products
  resources :products
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'

  get '/help', to: 'static_pages#help'

  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/admin', to: 'orders#admin'
  get '/search', to: 'products#search'
  mount Sidekiq::Web => '/sidekiq'
  resources :microposts
  resources :users
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :account_activations, only: [:edit]

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_many :line_items
  has_many :orders, through: :line_items
  belongs_to :user


  # searchable auto_index: false do
  #   text :description
  #   string :title
  #   string :pin
  # end
  # validates :title, :description, :image_url, presence: true
  # validates :price, numericality: {greater_than_or_equal_to: 0.01}
  #
  # validates :title, uniqueness: true

  # validates :title, length: {minimum: 10}
  mount_uploader :image, PictureUploader

  def self.newest_products
    Product.order(id: :desc).limit(5)
  end

  def decorate
    @decorate ||= ProductDecorator.new self
  end

  private

  # ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Items present')
      return false
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    if logged_in?
      add_breadcrumb "home", root_path
      add_breadcrumb "Products"
      @products = Product.where user_id: current_user.id
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_user.products.build(product_params)
    respond_to do |format|
      if @product.save
        SolrProduct.add_product ({:id => @product.id, :title => @product.title, :stock => @product.stock, :price => @product.price,
                                  :description => @product.description, :pin => @product.pin,
                                  :category_id => @product.category_id, :image_url => @product.image_url})
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def search
    add_breadcrumb "home", root_path
    add_breadcrumb "search"
    @solr_search = SolrProduct.search_products params[:search], params[:page]
    @total_results = @solr_search['total_results']
    @products = @solr_search['ids'].any? ? Product.where(id: @solr_search['ids']) : []
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image, :price, :category_id, :stock)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <%= form_for(@product) do |f| %>
      <%= render 'shared/error_messages', object: @product %>
      <div class="field">
        <%= f.label :title %><br>
        <%= f.text_field :title , class: 'form-control'%>
      </div>
      <div class="field">
        <%= f.label :description %><br>
        <%= f.text_area :description , class: 'form-control'%>
      </div>
      <div class="field">
        <%= f.label :image %><br>
        <span class="picture">
          <%= f.file_field :image %>
        </span>
      </div>
      <div class="field">
        <%= f.label :price %><br>
        <%= f.text_field :price , class: 'form-control'%>
      </div>
      <div class="field">
        <%= f.label :stock %><br>
        <%= f.text_field :stock , class: 'form-control'%>
      </div>
      <div class="field">
        <%= f.label :category_id %><br>

        <%= f.select :category_id, Category.get_categories, prompt: "Select a category" , class: 'form-control'%>
      </div>
      <div class="actions">
        <%= f.submit "Create New Product" , class: "btn btn-primary"%>
      </div>
    <% end %>
  </div>
</div>

app/views/products/_product.html.erb
<div class="col-md-4 col-lg-3 col-sm-6 col-xs-10">
  <div class="panel panel-success">
    <div class="panel-heading">
             <%= product.decorate.link%>
    </div>
    <div class="panel-body">
      <div class="text-center">
        <%= link_to product_path(product) do %>
          <%= image_tag product.image_url :medium_icon%>
        <%end%>
      </div>
      <div class="text-center">
        <p>
          <strong><%= product.category.title%></strong>
        </p>
        <p>
          Price: $<%= number_with_precision(product.price, precision: 2) %>
        </p>
      </div>
      <div class="text-center">
        <% if product.stock <= 0 %>
          Out Of Stock
        <% else %>
          <%= button_to "Add to cart", line_items_path(:product_id => product), class: "btn btn-success"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recommanded Items</h1>

<% if @products.present? %>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Price</th>
      <th>Pin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%= image_tag(product.image_url) %></td>
        <td><%= product.price %></td>
        <td><%= product.pin %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

    <% end %>
  </tbody>
</table>
<% end %>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

app/views/products/search.html.erb
<div class="row">
  <div class="col-md-9 col-md-offset-1">
      <div class="col-md-12">
        <h3> Search results </h3>
        <span> Found <%= pluralize(@total_results, 'result')%> </span>
      </div>
      <div class="text-right">
        <% @products.each do |product| %>
          <div class="row search">
            <div class="col-md-3 text-center">
              <%= link_to product_path(product) do %>
                <%= image_tag product.image_url(:medium_icon) %>
              <% end %>
            </div>
            <div class="col-md-9">
              <h4>
                <%= link_to product do %>
                  <%= product.title %>
                <% end %>
              </h4>

              <p>
                <strong> $<%= product.price %></strong>
              </p>
              <p> PIN: <%= product.pin %> </p>
              <% if product.stock <= 0 %>
                <h2>
                  <b>Out Of Stock</b>
                </h2>
              <% else %>
                <%= button_to "Add to cart", line_items_path(:product_id => product), class: "btn btn-success" %>
              <% end %>
              <p><%= simple_format product.description.truncate_words(50) %></p>
              <div class="text-right">
                <%= link_to "Read More", product_path(product) %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="text-right">
        <%= will_paginate @solr_search["ids"] %>
      </div>
  </div>
</div>

app/views/products/show.html.erb
<% if !@product.nil? %>
   <div class="row">
      <div class="col-md-12">
       <h1><%= @product.title %></h1>
     </div>
  </div>
  <div class="row">
   <div class="col-md-3 col-xs-offset-1">
    <%= image_tag @product.image_url :medium_icon %>
   </div>
   <div class="col-md-6">
    <div class="row">
     <div class="col-md-12">
      <p class="description">
        <%= @product.description.html_safe %>
      </p>
     </div>
    </div>
    <div class="row">
      <div class="col-md-1">
        <h2 class="product-price">$<%= @product.price %></h2>
      </div>
      <div class="col-md-2">
        <% if @product.stock > 0%>
          <%= button_to "Add to cart", line_items_path(:product_id => @product), class: "btn btn-success"%>
        <%else%>
          <span class="monospaced"><h2>Out Of Stock<h2></span>
        <% end %>
      </div>
    </div><!-- end row -->
    <div class="row">
      <div class="col-md-2">
        <%= link_to image_tag('social-facebook-box-blue-icon.png'), 'http://www.facebook.com/sharer.php?u=' + request.fullpath + '&p[images][0]=' + @product.image_url, :target => :blank %>
        <%= link_to image_tag('1468932807_twitter2.png'), "https://twitter.com/intent/tweet?source=webclient&text=" + @product.title + "+" + request.fullpath, :target => :blank %>
      </div>
    </div>
  </div>
<% end %>