config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  resources :categories
  resources :orders
  resources :line_items
  resources :carts
  resources :products
  resources :products
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'

  get '/help', to: 'static_pages#help'

  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/admin', to: 'orders#admin'
  get '/search', to: 'products#search'
  mount Sidekiq::Web => '/sidekiq'
  resources :microposts
  resources :users
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :account_activations, only: [:edit]

end

app/views/layouts/_breadcrumb.html.erb
<%= render_breadcrumbs %>

app/views/layouts/_footer.html.erb
<footer class="footer navbar-fixed-bottom navbar-inverse">
    <div class="container">
        <small>
         The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
         by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
        </small>
        <nav>
         <ul nav navbar-nav navbar-right>
             <li><%= link_to "About",   about_path %></li>
             <li><%= link_to "Contact", contact_path %></li>
             <li><a href="http://news.railstutorial.org/">News</a></li>
            </ul> 
        </nav>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="container">
  <div class="navbar-header">
   <%= link_to "Book Shop", root_path, id: "logo" %>

  <button id="navbarToggle" type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapsable-nav" aria-expanded="false">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
 </div>
    <nav id="collapsable-nav" class="collapse navbar-collapse">
       <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home",   root_path %></li>
          <li><%= link_to "Help",   help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "products", products_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <% if current_user.admin? %>
                <li><%= link_to "Order Management", admin_path %></li>
              <% else %>
                <li><%= link_to "Check Your Order", orders_path %></li>
              <% end %>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
          <li><%= link_to "Sign Up", signup_path %></li>
        <% end %>
        </ul>
    </nav>
  </div>
</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_vertical_bar.html.erb
<nav class="navbar navbar-inverse sidebar" role="navigation">
    <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button id="navbarToggle1" type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Category</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
          <%= link_to root_path do%>
          All<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-book"></span>
          <% end %>
        </li>
        <% Category.all.each do |category| %>
          <li ><%= link_to category_path(category) do%>
            <%= category.title %><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-book"></span>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %></head>
<body>

  <%= render 'layouts/header' %>

  <%= render 'layouts/vertical_bar' %>
  <div class="main">
      <div class="rows">
        <div class="col-md-2 col-md-offset-1">
          <h4><%= render 'layouts/breadcrumb' %> </h4>
        </div>
        <div class="col-md-7">
          <%= form_tag("/search", method: "get", role:"search") do %>
            <div class="input-group" class="search-products">
               <%= text_field_tag(:search, params[:search], placeholder: "Search", class: "form-control") %>
               <div class="input-group-btn">
                    <%= button_tag "", type: 'submit', class: "btn btn-default" do%>
                      <span class="glyphicon glyphicon-search"></span>
                    <% end %>
               </div>
            </div>
          <% end %>
        </div>
      </div>

    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>